apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      automountServiceAccountToken: false
      initContainers:
        - name: keycloak-chown
          command:
            - wget 
            - https://github.com/MinBZK/keycloak-theme/releases/download/v1.2.0/keycloak-nl-design-system.jar
            - -O 
            - /opt/keycloak/providers/keycloak-nl-design-system.jar
          image: busybox:1.37.0
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath:  /opt/keycloak/providers/
              name: keycloak-provider
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0.1
          args:
            ["start", "--proxy-headers=forwarded", "--features=preview", "--hostname-strict=false", "--spi-theme-welcome-theme=nl-design-system" ]
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: basis-keycloak-sec-keycloak
                  key: username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: basis-keycloak-sec-keycloak
                  key: password
            - name: KC_PROXY
              value: "edge"
            - name: ORGANIZATION
              value: "Ministerie van Binnenlandse Zaken en Koninkrijksrelaties"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME
              value: "https://id.la-suite.apps.digilab.network"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://basis-keycloak-cluster-db-rw/keycloak"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: basis-keycloak-sec-postgres
                  key: username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: basis-keycloak-sec-postgres
                  key: password
            - name: KC_HOSTNAME_ADMIN
              value: "https://id.la-suite.apps.digilab.network"
            # - name: KC_FEATURES
            #   value: "hostname"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
          volumeMounts:
            - name: keycloak-provider
              mountPath: /opt/keycloak/providers/
      volumes:
        - name: keycloak-provider
          emptyDir: {}
