apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-db
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3

  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: basis-keycloak-sec-postgres

  storage:
    storageClass: managed-csi-premium
    size: 2Gi

  enableSuperuserAccess: true
  superuserSecret:
    name: basis-keycloak-sec-postgres-super

  postgresql:
    parameters:
      shared_buffers: "128MB"

  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
