apiVersion: v1
kind: Secret
metadata:
  name: sec-postgres
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:qZUtsn2+APtVHynLXOhVSsLFQUswq7Wfcw==,iv:4HmrETZuv78ufNVz8kSGlRczdK2rxfyQMrM018kmRTI=,tag:S7BIUoQVLmo9V0u+43JULA==,type:str]
  username: ENC[AES256_GCM,data:3yfSdWnptok=,iv:QYKMPvgajf3CRmb6cEr1zYWzqHnyOiGVt2+lzrrxeBg=,tag:0qkMjyghQfXzBAsa+RtKDg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ju3xfm27kpus9wv9we6l5qr00ul23uj5jfxxz3skv6vjagtkasdsuwsqsp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RnEyTk5CTFQyRDZMYi9t
        TGdqSks4VWx5dXhYcmNqeTNrNkc4Ry94czFJCkI4QjMvMVNPQlRIZ3hhK1JyVEM3
        MGNFcXRKYXAxSUlNZTdsSEZMbDE4ZWMKLS0tIHM4bmpqa2p0OWpkZmZXUCtXdXA5
        bGFaREJWQld1Y0htOXhvdVBTejMyVG8Kqa5O55CHPzfBsq46GTEZvvpe4Jhi7nOt
        BSOiv/VtAh0m6KFoAdANDS8h8+hGlC1lEHkf0hKb0rtGA0qk+PYv/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-21T15:07:04Z"
  mac: ENC[AES256_GCM,data:4W/h00GykPlMcb0Bn/xf5zhESReDI/5jOCp5dfuzvVlPh/QyCH++teQ/tEhMd7N2z+Z0IoHTsN8ED3QmXwM4gaIydvgi0yLBue8BIQ8HCWkPMFWNTmY1TATJCi763Eki2hHo9oHmUHaKktmyEPYsCRHYo2mBmHwvmLW+fPn2vz4=,iv:zQFtVmm1RJ81BLrUb8bochvVhkPUbutDy8IyCy5P8PI=,tag:sKQlC1d1osSbZQWjCrCuuw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
