creation_rules:
  - path_regex: manifests/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: "age1ju3xfm27kpus9wv9we6l5qr00ul23uj5jfxxz3skv6vjagtkasdsuwsqsp"
  - path_regex: overlays/.*\.yaml$
    encrypted_regex: ^.+$
    age: "age1ju3xfm27kpus9wv9we6l5qr00ul23uj5jfxxz3skv6vjagtkasdsuwsqsp"

    