apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  labels:
    app.kubernetes.io/component: vault
spec:
  template:
    spec:
      containers:
        - name: vault
          env:
            - name: VAULT_CLUSTER_ADDR
              value: "http://vault-svc:8201" # this might change if you add a prefix of suffix