apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - configmap.yaml
  - admin-credentials.yaml
  - grafana-auth.yaml
  - pvc.yaml

namePrefix: grafana-

commonLabels:
  minbzk.github.io/name: grafana

buildMetadata: [originAnnotations]
