apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml

namePrefix: mailcatcher-

commonLabels:
  minbzk.github.io/name: mailcatcher

buildMetadata: [originAnnotations]
