apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefullset.yaml
  - service.yaml
  - ingress.yaml

namePrefix: vault-

labels:
  - pairs:
      app.kubernetes.io/name: vault


buildMetadata: [originAnnotations]

configMapGenerator:
  - name: vault-config
    files:
      - config.hcl
