apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sfs
  labels:
    app.kubernetes.io/component: vault
spec:
  serviceName: vault
  updateStrategy:
    type: OnDelete
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: vault
  template:
    metadata:
      labels:
        app.kubernetes.io/component: vault
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 100
        fsGroup: 1000
      containers:
        - name: vault
          image: hashicorp/vault:1.16.1
          ports:
            - containerPort: 8200
              name: vault-api
            - containerPort: 8201
              name: http-internal
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SKIP_CHOWN
              value: "true"
            - name: SKIP_SETCAP
              value: "true"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VAULT_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VAULT_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"
            - name: VAULT_CLUSTER_ADDR
              value: "http://vault-svc:8201"
            - name: VAULT_API_ADDR
              value: "http://$(POD_IP):8200"
            - name: VAULT_RAFT_PATH
              value: "/vault/data"
            - name: VAULT_LOG_LEVEL
              value: "trace"
            - name: VAULT_RAFT_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - server
          volumeMounts:
            - name: config
              mountPath: /vault/config
            - name: data
              mountPath: /vault/data
      volumes:
        - name: config
          configMap:
            name: vault-config
        - name: data
          persistentVolumeClaim:
            claimName: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: azurefile
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
