apiVersion: v1
kind: Secret
metadata:
    name: sec-alertmanager
type: Opaque
stringData:
    slack_api_url: ENC[AES256_GCM,data:2kPR4yxk0dzvlpYOuAWQGRyS2hWlATWosSMv0TK/KM1/glx3uDrotb27pIDgftmBwNbn5mMMsxIK,iv:oOC+LVUaqnRaQqgsmfDvrn/6X9Y+P59E7w+VkhZl6IU=,tag:Ay3FqpXsCr7+j0PDCusxEA==,type:str]
    oauth2_client_secret: ENC[AES256_GCM,data:f7opkzOf6mCSgeBWoFG8OvUJGU5oGKtUXR9lNjWtT6I=,iv:yW5CFtGHHOLgMGSAHjXiCK6Cp6rVkTBe2pY/slQe064=,tag:QQFVkpcZWRTCFuzNTem2Zg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ju3xfm27kpus9wv9we6l5qr00ul23uj5jfxxz3skv6vjagtkasdsuwsqsp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhb0FjQjZ0WGZCdWtDbU40
            NFp2RFlxNG9La3g1NkxHVXlxcC9mRE4zbVVvCmJXU2xDTXFDalZYalNaTGZkRHNu
            TEd5c2NlMkhOWjdMcDJDbFhTQldnUE0KLS0tIHR6blppYVBLcnU2VVZyWm0rYTN5
            OHg4T3YySmdhd0VOWG5BcDJOV1pRaVUKgBPu3QqO6vncMVeuHF5HX1bW0SGoalkt
            N6VW9KFBPCUaLWHJJwsX8gzvPgpKlJ1S6BaFden1QkKurS0ig2CRCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-11T14:49:30Z"
    mac: ENC[AES256_GCM,data:XRIsVzxfxn1iJaGzQg2zazyi4J8UTlJAEXpFoep/mCNFcWjQBLIHPV2I9MKKtHutmYBUpdLjNbtW2fVPnp2CnpWWukSwHbi8qeDKMWEAAQvAo52nKYiZmWmsrOIZos+BRnrqz8r9ndyVhZTe34/ztBARKRWrR3BzxeWmAbRf7WY=,iv:fD7sC0GXoQKsUenROFl6T0clydcmFUD+s3WrzFVdYwY=,tag:veXW9GyiLrUpTeOiPHDMSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
