apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sfs
  labels:
    app: alertmanager
spec:
  replicas: 2
  serviceName: svc-headless
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 65534
      containers:
        - name: alertmanager-configmap-reload
          image: "quay.io/prometheus-operator/prometheus-config-reloader:v0.66.0"
          args:
            - --watched-dir=/etc/alertmanager
            - --reload-url=http://127.0.0.1:9093/-/reload
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
        - name: alertmanager
          securityContext:
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
            fsGroup: 65534
          image: prom/alertmanager:v0.27.0
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: SLACK_API_URL
              valueFrom:
                secretKeyRef:
                  name: sec-alertmanager
                  key: slack_api_url
            - name: OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sec-alertmanager
                  key: oauth2_client_secret
          args:
            - --storage.path=/alertmanager
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --cluster.advertise-address=[$(POD_IP)]:9094
            - --cluster.listen-address=0.0.0.0:9094
            - --cluster.peer=basis-alertmanager-sfs-0.basis-alertmanager-svc-headless.tn-openbsw-basis.svc.cluster.local:9094
            - --cluster.peer=basis-alertmanager-sfs-1.basis-alertmanager-svc-headless.tn-openbsw-basis.svc.cluster.local:9094
          ports:
            - name: http
              containerPort: 9093
              protocol: TCP
            - name: clusterpeer-tcp
              containerPort: 9094
              protocol: TCP
            - name: clusterpeer-udp
              containerPort: 9094
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
            - name: storage
              mountPath: /alertmanager
            - name: slack-secret-volume
              mountPath: /etc/secrets/slack_api_url
              subPath: slack_api_url
      volumes:
        - name: config
          configMap:
            name: alertmanager-config
        - name: slack-secret-volume
          secret:
            secretName: sec-alertmanager
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
