apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sfs
  labels:
    app: alertmanager
spec:
  replicas: 2
  serviceName: alertmanager
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 65534
      containers:
        - name: alertmanager-configmap-reload
          image: "quay.io/prometheus-operator/prometheus-config-reloader:v0.66.0"
          args:
            - --watched-dir=/etc/alertmanager
            - --reload-url=http://127.0.0.1:9093/-/reload
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
        - name: alertmanager
          securityContext:
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
          image: prom/alertmanager:v0.27.0
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          args:
            - --storage.path=/alertmanager
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --cluster.advertise-address=[$(POD_IP)]:9094
            - --cluster.listen-address=0.0.0.0:9094
            - --cluster.peer=release-name-alertmanager-0.release-name-alertmanager-headless:9094
            - --cluster.peer=release-name-alertmanager-1.release-name-alertmanager-headless:9094
          ports:
            - name: http
              containerPort: 9093
              protocol: TCP
            - name: clusterpeer-tcp
              containerPort: 9094
              protocol: TCP
            - name: clusterpeer-udp
              containerPort: 9094
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
            - name: storage
              mountPath: /alertmanager
      volumes:
        - name: config
          configMap:
            name: config
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi



