apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - postgresql-cluster.yaml

namePrefix: keycloak-

labels:
  - pairs:
      app.kubernetes.io/name: keycloak
    includeSelectors: true

buildMetadata: [originAnnotations]
